=== VitaliiBashta/L2Jts/data/xmlscript/community/leaseTransform/leaseTransform.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (transform)*>
<!ELEMENT transform (level|skill|bonus|description|times)*>
<!ATTLIST transform
	id CDATA #REQUIRED
	nameRU CDATA #REQUIRED
	nameEN CDATA #REQUIRED>	
<!ELEMENT level (#PCDATA)>
<!ATTLIST level
	min CDATA #REQUIRED
	max CDATA #REQUIRED>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	skillId CDATA #REQUIRED
	skillLevel CDATA #REQUIRED>
<!ELEMENT bonus (#PCDATA)>
<!ATTLIST bonus
	str CDATA #IMPLIED
	int CDATA #IMPLIED
	con CDATA #IMPLIED
	dex CDATA #IMPLIED	
	wit CDATA #IMPLIED
	men CDATA #IMPLIED>	
<!ELEMENT description (#PCDATA)>
<!ATTLIST description
	ru CDATA #REQUIRED
	en CDATA #REQUIRED>
<!ELEMENT times (time)*>
<!ELEMENT time (#PCDATA)>
<!ATTLIST time
	key CDATA #REQUIRED
	minute CDATA #REQUIRED
	itemId CDATA #REQUIRED
	itemCount CDATA #REQUIRED>

=== VitaliiBashta/L2Jts/data/xmlscript/community/leaseTransform/leaseTransform.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "leaseTransform.dtd">
<!-- 
 (c)Mangol
 COMBAT - боевые трансформы,
 так же в них можно указывать бонусы к статам str,
 con и тд.!! Ни в коем случае не указывать для других категорий трансформ
 -->
<list>
	<!-- COMBAT -->
	<transform id="1" nameRU="Зверь Знамения" nameEN="Onyx Beast">
		<level min="1" max="85"/>
		<skill skillId="617" skillLevel="1"/>
		<bonus str="10" int="4" con="2" dex="6" wit="5" men="4"/>
		<description ru="Возможно перевоплотиться в Зверя Знамения" en="That transforms you to Omen Beast" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="2" nameRU="Рыцарь Рока" nameEN="Death Blader">
		<level min="1" max="85"/>
		<skill skillId="618" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Рыцаря Рока" en="That transforms you to Death Blader" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="3" nameRU="Вероотступник" nameEN="Heretic">
		<level min="1" max="85"/>
		<skill skillId="670" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Вероотступника" en="That transforms you to Heretic" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="4" nameRU="Мастер Долин" nameEN="Veil Master">
		<level min="1" max="85"/>
		<skill skillId="671" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Мастера Долин" en="That transforms you to Veil Master" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="5" nameRU="Саблезубый Тигр" nameEN="Saber Tooth Tiger">
		<level min="1" max="85"/>
		<skill skillId="672" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Саблезубого Тигра" en="That transforms you to Saber Tooth Tiger" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>	
	<transform id="6" nameRU="Сфинкс" nameEN="Oel Mahum">
		<level min="1" max="85"/>
		<skill skillId="673" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Сфинкса" en="That transforms you to Oel Mahum" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="7" nameRU="Кукла" nameEN="Doll Blader">
		<level min="1" max="85"/>
		<skill skillId="674" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Куклу" en="That transforms you to Doll Blader" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="126" nameRU="Трейкхан" nameEN="Treykan">
		<level min="1" max="85"/>
		<skill skillId="6649" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Трейкхана" en="That transforms you to Treykan" />	
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>	
	<transform id="202" nameRU="Апостол Грааля" nameEN="Grail Apostle">
		<level min="1" max="85"/>
		<skill skillId="542" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Апостола Грааля" en="That transforms you to Grail Apostle" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="204" nameRU="Единорог" nameEN="Unicorn">
		<level min="1" max="85"/>
		<skill skillId="545" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Единорога" en="That transforms you to Unicorn" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="208" nameRU="Рыцарь Лилим" nameEN="Lilim Knight">
		<level min="1" max="85"/>
		<skill skillId="548" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Рыцаря Лилим" en="That transforms you to Lilim Knight" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="211" nameRU="Голем Стражник" nameEN="Golem Guardian">
		<level min="1" max="85"/>
		<skill skillId="551" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Голема Стражника" en="That transforms you to Golem Guardian" />	
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="214" nameRU="Инфернальный Дрейк" nameEN="Inferno Drake">
		<level min="1" max="85"/>
		<skill skillId="554" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Инфернального Дрейка" en="That transforms you to Inferno Drake" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="217" nameRU="Панцирный Дракон" nameEN="Dragon Bomber">
		<level min="1" max="85"/>
		<skill skillId="557" skillLevel="1"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Панцирного Дракона" en="That transforms you to Dragon Bomber" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="252" nameRU="Божественный Рыцарь" nameEN="Divine Knight">
		<level min="1" max="85"/>
		<skill skillId="657" skillLevel="3"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Божественного Рыцаря" en="That transforms you to Divine Knight" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>	
	<transform id="253" nameRU="Божественный Воитель" nameEN="Divine Warrior">
		<level min="1" max="85"/>
		<skill skillId="656" skillLevel="3"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Божественного Воителя" en="That transforms you to Divine Warrior" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="254" nameRU="Божественный Разбойник" nameEN="Divine Rogue">
		<level min="1" max="85"/>
		<skill skillId="658" skillLevel="3"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Божественного Разбойника" en="That transforms you to Divine Rogue" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="255" nameRU="Божественный Целитель" nameEN="Divine Healer">
		<level min="1" max="85"/>
		<skill skillId="661" skillLevel="3"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Божественного Целителя" en="That transforms you to Divine Healer" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
	</transform>
	<transform id="256" nameRU="Божественный Чародей" nameEN="Divine Wizard">
		<level min="1" max="85"/>
		<skill skillId="659" skillLevel="3"/>
		<bonus str="3" int="4" con="2" dex="6" wit="5" men="4"/>		
		<description ru="Возможно перевоплотиться в Божественного Чародея" en="That transforms you to Divine Wizard" />
		<times>
			<time key="1" minute="20" itemId="57" itemCount="2" />
			<time key="2" minute="40" itemId="57" itemCount="3" />
			<time key="3" minute="60" itemId="57" itemCount="5" />
		</times>
