=== VitaliiBashta/L2Jts/data/xmlscript/dtd/talisman_event.dtd
<!ELEMENT list (choice)*>
        <!ELEMENT choice (pay|success|fail)*>
        <!ATTLIST choice
                id CDATA #REQUIRED
                chance CDATA #REQUIRED>
        <!ELEMENT pay (item)*>
        <!ELEMENT item (#PCDATA)>
        <!ATTLIST item
                count CDATA #REQUIRED
                id CDATA #REQUIRED>
        <!ELEMENT success (item)*>
        <!ELEMENT fail (item)*>

=== VitaliiBashta/L2Jts/data/xmlscript/items/talisman_event.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "talisman_event.dtd">
<list>
	<choice id="1" chance="50">
		<pay>
			<item id="57" count="1000"/>
		</pay>
		<success>
			<item id="57" count="1000"/>
		</success>
		<fail>
			<item id="57" count="1000"/>
		</fail>
	</choice>
</list>
