=== VitaliiBashta/L2Jts/data/xmlscript/phantoms/spawn.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (spawn)*>
<!ELEMENT spawn (territory)*>
<!ATTLIST spawn 
	type CDATA #REQUIRED
	count CDATA #REQUIRED
	gradeMin CDATA #REQUIRED
	gradeMax CDATA #REQUIRED>
<!ELEMENT territory (add)*>
<!ELEMENT add (#PCDATA)>
<!ATTLIST add 
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED>

=== VitaliiBashta/L2Jts/data/spawn/spawn_old/22_24.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">

<list>
	<spawn count="2" respawn="45" respawn_random="0" period_of_day="none">
		<territory>
			<add x="72400" y="218506" zmin="-3902" zmax="-2902"/>
			<add x="73740" y="216446" zmin="-3902" zmax="-2902"/>
			<add x="76729" y="218035" zmin="-3902" zmax="-2902"/>
			<add x="74207" y="219409" zmin="-3902" zmax="-2902"/>
		</territory>
		<npc id="20989"/>
		<!--Lageos-->
	</spawn>
</list>
